exports.dom2t = {
    NAME: "Domination",
    WIDTH: 5550,
    HEIGHT: 5550,
    X_GRID: 15,
    Y_GRID: 15,
    DOMINATION_LOOP: true,
    NUMBER_OF_DOMS: 5,
    BOTS: 5,
    MAX_FOOD: 50,
    TEAMS: 2,
    ROOM_SETUP: [
      [ "bas1", "bap1", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "bap1", "bap1", "obsr", "obsr", "obsr", "obsr", "obsr", "arcl", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "domN", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arc2", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "arcl", "domW", "obsr", "obsr", "arc2", "nest", "domC", "nest", "arc2", "obsr", "obsr", "domE", "arcl", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arc2", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "domS", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arcl", "obsr", "obsr", "obsr", "obsr", "obsr", "bap2", "bap2" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "bap2", "bas2" ]
    ],  
}