exports.dday = {
  NAME: "D-Day",
  WIDTH: 6500,
  HEIGHT: 6500,
  X_GRID: 33,
  Y_GRID: 33,
  BOTS: 5,
  MAX_FOOD: 50,
  TEAMS: 2,
  ROOM_SETUP: [
    [ "bas1", "bas1", "bas1", "bas1", "bas1", "bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1" ],
    [ "bas1", "bas1", "bas1", "bas1", "bas1", "bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1","bas1" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm" ],
    [ "norm", "norm", "norm", "norm", "norm", "bmaz","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","norm","norm","norm","norm","norm","norm","bmaz","norm","norm","bmaz","bmaz","bmaz","bmaz","norm","bmaz","bmaz","norm","norm","norm","norm","bmaz","bmaz","bmaz","bmaz","norm","bmaz","bmaz" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","norm","bmaz","bmaz","bmaz","bmaz","norm","norm","norm","bmaz","norm","norm","bmaz","norm","norm","norm","bmaz","bmaz","bmaz","bmaz","bmaz","norm","norm","norm","norm","norm","norm","bmaz" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","norm","norm","norm","norm","norm","bmaz","norm","norm","norm","bmaz","norm","norm","norm","bmaz","norm","norm","norm","norm","norm","norm","norm","bmaz","bmaz","bmaz","bmaz","norm","bmaz" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","norm","bmaz","bmaz","norm","norm","bmaz","norm","bmaz","norm","norm","norm","bmaz","bmaz","bmaz","bmaz","norm","bmaz","norm","bmaz","bmaz","norm","norm","bmaz","norm","bmaz","norm","bmaz" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","bmaz","norm","bmaz","bmaz","norm","bmaz","norm","norm","bmaz","norm","bmaz","bmaz","dom3","norm","bmaz","norm","norm","bmaz","bmaz","norm","bmaz","norm","norm","norm","bmaz","norm","bmaz" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","norm","norm","bmaz","norm","norm","norm","norm","bmaz","bmaz","norm","norm","bmaz","norm","norm","bmaz","bmaz","norm","norm","norm","norm","norm","bmaz","norm","norm","bmaz","norm","bmaz" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","norm","norm","norm","norm","bmaz","bmaz","norm","bmaz","norm","norm","norm","norm","norm","norm","norm","norm","bmaz","norm","bmaz","norm","norm","bmaz","bmaz","norm","bmaz","norm","bmaz" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","bmaz","norm","norm","norm","norm","norm","norm","bmaz","norm","norm","norm","bmaz","bmaz","norm","bmaz","norm","bmaz","norm","norm","bmaz","norm","bmaz","dom3","norm","bmaz","norm","bmaz" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","norm","bmaz","norm","norm","norm","norm","norm","bmaz","norm","bmaz","norm","bmaz","norm","norm","bmaz","norm","norm","bmaz","norm","bmaz","norm","bmaz","bmaz","norm","bmaz","norm","bmaz" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","norm","bmaz","bmaz","bmaz","bmaz","norm","bmaz","bmaz","bmaz","bmaz","norm","bmaz","norm","bmaz","norm","norm","norm","bmaz","bmaz","norm","norm","norm","bmaz","norm","bmaz","norm","bmaz" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","norm","bmaz","norm","norm","norm","bmaz","norm","norm","norm","bmaz","norm","norm","norm","bmaz","norm","bmaz","norm","norm","norm","norm","norm","norm","bmaz","norm","bmaz","norm","bmaz" ],
    [ "norm", "norm", "norm", "norm", "norm", "norm","bmaz","norm","bmaz","norm","bmaz","bmaz","norm","norm","norm","bmaz","norm","bmaz","norm","bmaz","norm","norm","norm","norm","norm","norm","norm","bmaz","norm","norm","bmaz","norm","bmaz" ],
    [ "norm", "norm", "norm", "bmaz", "norm", "bmaz","norm","norm","norm","norm","norm","bmaz","norm","dom3","norm","bmaz","norm","norm","norm","bmaz","bmaz","norm","norm","bmaz","bmaz","bmaz","norm","bmaz","norm","norm","norm","norm","bmaz" ],
    [ "norm", "norm", "norm", "norm", "norm", "bmaz","norm","norm","bmaz","norm","norm","bmaz","norm","norm","norm","bmaz","bmaz","norm","bmaz","norm","bmaz","bmaz","bmaz","bmaz","norm","norm","norm","bmaz","norm","bmaz","bmaz","norm","bmaz" ],
    [ "norm", "norm", "norm", "norm", "norm", "bmaz","norm","bmaz","norm","norm","bmaz","bmaz","norm","bmaz","norm","bmaz","norm","norm","bmaz","norm","norm","bmaz","domi","bmaz","norm","bmaz","bmaz","bmaz","bmaz","bmaz","norm","bmaz","bmaz" ],
    [ "norm", "norm", "norm", "bmaz", "norm", "norm","norm","bmaz","norm","norm","bmaz","norm","bmaz","norm","norm","bmaz","norm","norm","bmaz","norm","norm","norm","norm","bmaz","norm","norm","bmaz","norm","norm","norm","norm","norm","bmaz" ],
    [ "norm", "norm", "norm", "bmaz", "norm", "norm","norm","norm","bmaz","norm","norm","norm","norm","bmaz","norm","norm","norm","norm","norm","norm","norm","norm","norm","bmaz","norm","norm","norm","norm","norm","norm","norm","norm","bmaz" ],
    [ "norm", "norm", "norm", "norm", "norm", "bmaz","norm","norm","norm","norm","norm","norm","norm","norm","norm","bmaz","norm","norm","bmaz","norm","norm","norm","norm","bmaz","norm","norm","norm","norm","bmaz","norm","bmaz","domi","bmaz" ],
    [ "norm", "norm", "norm", "norm", "norm", "bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz","bmaz" ]
  ],
}