exports.maze = {
  NAME: "Maze",
  WIDTH: 4250,
  HEIGHT: 4250,
  RANDOM_COLORS: true,
  X_GRID: 12,
  Y_GRID: 12,
  BOTS: 5,
  MAZE: 32,
  MAX_FOOD: 50,
  ROOM_SETUP: [
    [ "obsr", "obsr", "obsr", "obsr", "arc2", "obsr", "roid", "obsr", "obsr", "obsr", "obsr", "arcl" ],
    [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
    [ "obsr", "obsr", "rock", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "rock", "obsr", "obsr" ],
    [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
    [ "norm", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "norm", "norm", "norm", "norm" ],
    [ "norm", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "norm", "norm", "norm", "norm" ],
    [ "roid", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "norm", "norm", "norm", "roid" ],
    [ "norm", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "norm", "norm", "norm", "norm" ],
    [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
    [ "obsr", "obsr", "rock", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "rock", "obsr", "obsr" ],
    [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
    [ "obsr", "obsr", "obsr", "obsr", "arc2", "obsr", "roid", "obsr", "obsr", "obsr", "obsr", "arcl" ]
  ],  
}