exports.siege = {
    NAME: "Siege",
    TEAMS: 1,
    WIDTH: 4250,
    HEIGHT: 4250,
    X_GRID: 16,
    Y_GRID: 16,
    BOTS: 0,
    MAX_FOOD: 10,
    ROOM_SETUP: [
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arcl", "arc2", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr"],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "wall", "wall", "boss", "boss", "wall", "wall", "obsr", "obsr", "obsr", "obsr", "obsr"],
      [ "obsr", "obsr", "obsr", "obsr", "wall", "wall", "wall", "boss", "boss", "wall", "wall", "wall", "obsr", "obsr", "obsr", "obsr"],
      [ "obsr", "obsr", "obsr", "wall", "wall", "wall", "nest", "obsr", "obsr", "nest", "wall", "wall", "wall", "obsr", "obsr", "obsr"],
      [ "obsr", "obsr", "wall", "wall", "wall", "norm", "obsr", "obsr", "obsr", "obsr", "norm", "wall", "wall", "wall", "obsr", "obsr"],
      [ "obsr", "wall", "wall", "wall", "norm", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "norm", "wall", "wall", "wall", "obsr"],
      [ "obsr", "wall", "wall", "nest", "obsr", "obsr", "sanc1", "obsr", "obsr", "sanc2", "obsr", "obsr", "nest", "wall", "wall", "obsr"],
      [ "arc2", "boss", "boss", "obsr", "obsr", "obsr", "obsr", "spawn1", "spawn1", "obsr", "obsr", "obsr", "obsr", "boss", "boss", "arcl"],
      [ "arcl", "boss", "boss", "obsr", "obsr", "obsr", "obsr", "spawn1", "spawn1", "obsr", "obsr", "obsr", "obsr", "boss", "boss", "arc2"],
      [ "obsr", "wall", "wall", "nest", "obsr", "obsr", "sanc3", "obsr", "obsr", "sanc4", "obsr", "obsr", "nest", "wall", "wall", "obsr"],
      [ "obsr", "wall", "wall", "wall", "norm", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "norm", "wall", "wall", "wall", "obsr"],
      [ "obsr", "obsr", "wall", "wall", "wall", "norm", "obsr", "obsr", "obsr", "obsr", "norm", "wall", "wall", "wall", "obsr", "obsr"],
      [ "obsr", "obsr", "obsr", "wall", "wall", "wall", "nest", "obsr", "obsr", "nest", "wall", "wall", "wall", "obsr", "obsr", "obsr"],
      [ "obsr", "obsr", "obsr", "obsr", "wall", "wall", "wall", "boss", "boss", "wall", "wall", "wall", "obsr", "obsr", "obsr", "obsr"],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "wall", "wall", "boss", "boss", "wall", "wall", "obsr", "obsr", "obsr", "obsr", "obsr"],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arc2", "arcl", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr"],
    ],  
}