const 
 G1 = require('../gamemodes/developer').developer,
 G2 = require('../gamemodes/ffa').ffa,
 G3 = require('../gamemodes/o2tdm').o2tdm,
 G4 = require('../gamemodes/o4tdm').o4tdm,
 G5 = require('../gamemodes/2tdm').tdm2,
 G6 = require('../gamemodes/4tdm').tdm4,
 G7 = require('../gamemodes/2tmaze').maze2t,
 G8 = require('../gamemodes/4tmaze').maze4t,
 G9 = require('../gamemodes/2tdom').dom2t,
 G10 = require('../gamemodes/maze').maze,
 G11 = require('../gamemodes/mot').mot,
 G12 = require('../gamemodes/dday').dday;     
let list = [
  "Developer",
  "Developer",
  "Developer",
  "Developer",
  "Developer",
  "Developer",
  "Developer",
  "Developer",
  "Developer",
  "Developer",
  "Developer"
];
let config = {
  "Developer": G1,
  "FFA": G2,
  "Open 2TDM": G3,
  "Open 4TDM": G4,
  "2TDM": G5,
  "4TDM": G6,
  "2TDM Maze": G7,
  "4TDM Maze": G8,
  "Domination": G9,
  "Maze": G10,
  "Mothership": G11,
  "D-Day": G12
};

exports.output = {
  "host": "0.0.0.0",
  "servesStatic": true,
  "port": 3000,
  "logpath": "logger.php",
  "networkUpdateFactor": 24,
  "socketWarningLimit": 5,
  "networkFrontlog": 1,
  "networkFallbackTime": 150,
  "visibleListInterval": 1000,
  "gameSpeed": 1,
  "runSpeed": 1.5,
  "maxHeartbeatInterval": 30000,
  "sqlinfo":{
    "connectionLimit": 50,
    "host": "DEFAULT",
    "user": "root",
    "password": "DEFAULT",
     "database": "DEFAULT",
    "debug": false
  },
  "verbose": true,
  "WIDTH": 3250,
  "HEIGHT": 3250,
  "TESTING": false,
  "MODE": "ffa",
  "RANDOM_COLORS": false,
  "TEAMS": 0,
  "BANNED_CHARACTER_REGEX": "/[\uFDFD\u200E\u0000]/gi",
  "ROOM_SETUP": [
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "naorm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "nest", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "nest", "nest", "norm", "nest", "nest", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "nest", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"]
  ],
  "X_GRID": 9,
  "Y_GRID": 9,
  "DAMAGE_CONSTANT": 0.6,
  "KNOCKBACK_CONSTANT": 1,
  "ROOM_BOUND_FORCE": 0.01,
  "MAZE": false,
  "FOOD": [
    0,
    0.75,
    0.22,
    0.1,
    0.005,
    0,
    0
  ],
  "FOOD_NEST": [
    0,
    0.0,
    0.0,
    0.75,
    0.23,
    0.02,
    0
  ],
  "MAX_SKILL": 9,
  "SOFT_MAX_SKILL": 0.59,
  "TIER_1": 15,
  "TIER_2": 30,
  "TIER_3": 45,
  "TIER_4": 60,
  "SKILL_CAP": 60,
  "SKILL_SOFT_CAP": 0,
  "SKILL_CHEAT_CAP": 60,
  "SKILL_LEAK": 0,
  "STEALTH": 4,
  "MIN_SPEED": 0.001,
  "FOOD_AMOUNT": 0.001,
  "SKILL_BOOST": 5,
  "BOTS": 2,
  "GLASS_HEALTH_FACTOR": 2,
};

exports.base = {
  "host": "0.0.0.0",
  "servesStatic": true,
  "port": 3000,
  "logpath": "logger.php",
  "networkUpdateFactor": 24,
  "socketWarningLimit": 5,
  "networkFrontlog": 1,
  "networkFallbackTime": 150,
  "visibleListInterval": 1000,
  "gameSpeed": 1,
  "runSpeed": 1.5,
  "maxHeartbeatInterval": 30000,
  "DAMAGE_CONSTANT": 0.6,
  "KNOCKBACK_CONSTANT": 1,
  "ROOM_BOUND_FORCE": 0.01,
  "FOOD": [
    0,
    0.75,
    0.22,
    0.1,
    0.005,
    0,
    0
  ],
  "FOOD_NEST": [
    0,
    0.0,
    0.0,
    0.75,
    0.23,
    0.02,
    0
  ],
  "MAX_SKILL": 9,
  "SOFT_MAX_SKILL": 0.59,
  "TIER_1": 15,
  "TIER_2": 30,
  "TIER_3": 45,
  "TIER_4": 60,
  "SKILL_CAP": 60,
  "SKILL_SOFT_CAP": 0,
  "SKILL_CHEAT_CAP": 60,
  "SKILL_LEAK": 0,
  "STEALTH": 4,
  "MIN_SPEED": 0.001,
  "FOOD_AMOUNT": 0.001,
  "SKILL_BOOST": 5,
  "BOTS": 10,
  "GLASS_HEALTH_FACTOR": 2,
  "TESTING": false,
  "EVENT": 0
};

const rand = require("../lib/random.js");
let mode = list[rand.chooseChance(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)];
exports.output = config[mode]
if (!config[mode]) throw new Error("That gamemode does not exist!");
for (let key in config[mode]) exports.output[key] = config[mode][key];
if (config[mode].TEAMS) exports.output.MODE = "tdm";
if (!config[mode].TEAMS) exports.output.MODE = "ffa";
console.log(mode);
